### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by ebeatty1** [ebeatty1/install#1]
5/23/2019

- [x] Add htop to package list
- [x] Decide on which KeePass package to include
- [x] Decide on a PDF viewer to include (qpdfview?)
- [x] Check if the python-pywal package edits .bashrc and .xinitrc (if not, add code to edit them)
- [x] Start wal if wal isn't already running (wal -i ~/Pictures/)
- [ ] Add XFCE keybinds to remap window movement
- [ ] Include an option to sync to a remote server
- [ ] Fix the trackpad when installing on an X220
- [ ] Clear the Desktop
- [ ] Start and enable sshd.service if it isn't already running
